#!/usr/bin/env python3
from __future__ import annotations

import os
import json
from ftplib import FTP
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REMOTE_DIRS = ["web", "kurage_exbridge_jp"]
UPLOADS = [
    (ROOT / "web" / "kdeck.php", "kdeck.php"),
    (ROOT / "images" / "kdeck.png", "images/kdeck.png"),
    (ROOT / "images" / "kurage-icon.png", "images/kurage-icon.png"),
]


def load_env(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        os.environ.setdefault(key, value)


def connect() -> FTP:
    host = os.environ.get("HETEML_FTP_HOST", "ftp-exbridge.heteml.net")
    user = os.environ.get("HETEML_FTP_USER", "exbridge")
    password = os.environ["HETEML_FTP_PASS"]
    ftp = FTP()
    ftp.encoding = "utf-8"
    ftp.connect(host, 21, timeout=30)
    ftp.login(user, password)
    return ftp


def ensure_cwd(ftp: FTP, parts: list[str]) -> None:
    for part in parts:
        try:
            ftp.cwd(part)
        except Exception:
            ftp.mkd(part)
            ftp.cwd(part)


def upload_file(ftp: FTP, local: Path, remote: str) -> None:
    parent = Path(remote).parent
    base = ftp.pwd()
    if str(parent) != ".":
        ensure_cwd(ftp, list(parent.parts))
    with local.open("rb") as fh:
        ftp.storbinary("STOR " + Path(remote).name, fh)
    ftp.cwd(base)
    print(f"uploaded {remote}")


def upload_config(ftp: FTP) -> None:
    token = os.environ.get("KDECK_TOKEN", "")
    api_base = os.environ.get("KDECK_API_BASE", "http://exbridge.ddns.net:18301")
    if not token or token == "change-this-token":
        raise SystemExit("KDECK_TOKEN is not configured")
    body = (
        "<?php\n"
        "// Generated by scripts/deploy_web.py. Do not commit this file.\n"
        f"define('KDECK_API_BASE', {json.dumps(api_base, ensure_ascii=False)});\n"
        f"define('KDECK_TOKEN', {json.dumps(token, ensure_ascii=False)});\n"
    ).encode("utf-8")
    from io import BytesIO

    ftp.storbinary("STOR kdeck_config.php", BytesIO(body))
    print("uploaded kdeck_config.php")


def main() -> None:
    load_env(ROOT / ".env")
    ftp = connect()
    try:
        ensure_cwd(ftp, REMOTE_DIRS)
        for local, remote in UPLOADS:
            if local.is_file():
                upload_file(ftp, local, remote)
        upload_config(ftp)
    finally:
        ftp.quit()


if __name__ == "__main__":
    main()
