#!/usr/bin/env python3
from __future__ import annotations

import os
import json
import re
from ftplib import FTP
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REMOTE_DIRS = [part for part in os.environ.get("KDECK_FTP_REMOTE_DIR", "").split("/") if part]
UPLOADS = [(ROOT / "web" / "kdeck.php", "kdeck.php")]


def load_env(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        os.environ.setdefault(key, value)


def load_legacy_ftp_helper(path: Path) -> None:
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8", errors="ignore")
    mapping = {
        "FTP_HOST": "HETEML_FTP_HOST",
        "FTP_USER": "HETEML_FTP_USER",
        "FTP_PASS": "HETEML_FTP_PASS",
    }
    for legacy_key, env_key in mapping.items():
        if os.environ.get(env_key):
            continue
        match = re.search(rf"^{legacy_key}\s*=\s*(['\"])(.*?)\1", text, re.MULTILINE)
        if match:
            os.environ[env_key] = match.group(2)


def connect() -> FTP:
    host = os.environ["KDECK_FTP_HOST"]
    user = os.environ["KDECK_FTP_USER"]
    password = os.environ["KDECK_FTP_PASS"]
    ftp = FTP()
    ftp.encoding = "utf-8"
    ftp.connect(host, 21, timeout=30)
    ftp.login(user, password)
    return ftp


def ensure_cwd(ftp: FTP, parts: list[str]) -> None:
    for part in parts:
        try:
            ftp.cwd(part)
        except Exception:
            ftp.mkd(part)
            ftp.cwd(part)


def upload_file(ftp: FTP, local: Path, remote: str) -> None:
    parent = Path(remote).parent
    base = ftp.pwd()
    if str(parent) != ".":
        ensure_cwd(ftp, list(parent.parts))
    with local.open("rb") as fh:
        ftp.storbinary("STOR " + Path(remote).name, fh)
    ftp.cwd(base)
    print(f"uploaded {remote}")


def upload_config(ftp: FTP) -> None:
    token = os.environ.get("KDECK_TOKEN", "")
    api_base = os.environ.get("KDECK_API_BASE", "http://127.0.0.1:18301")
    if not token or token == "change-this-token":
        raise SystemExit("KDECK_TOKEN is not configured")
    values = {
        "KDECK_API_BASE": api_base,
        "KDECK_TOKEN": token,
        "KDECK_UI_TITLE": os.environ.get("KDECK_UI_TITLE", "kdeck"),
        "KDECK_UI_SUBTITLE": os.environ.get("KDECK_UI_SUBTITLE", "Codex CLI web console"),
        "KDECK_UI_DESCRIPTION": os.environ.get("KDECK_UI_DESCRIPTION", "Mobile web console for Codex CLI sessions."),
        "KDECK_RETURN_URL": os.environ.get("KDECK_RETURN_URL", ""),
        "KDECK_UI_ICON": os.environ.get("KDECK_UI_ICON", ""),
        "KDECK_OG_IMAGE": os.environ.get("KDECK_OG_IMAGE", ""),
    }
    lines = [
        "<?php",
        "// Generated by scripts/deploy_web.py. Do not commit this file.",
    ]
    lines.extend(
        f"define({json.dumps(key)}, {json.dumps(value, ensure_ascii=False)});"
        for key, value in values.items()
    )
    body = ("\n".join(lines) + "\n").encode("utf-8")
    from io import BytesIO

    ftp.storbinary("STOR kdeck_config.php", BytesIO(body))
    print("uploaded kdeck_config.php")


def main() -> None:
    load_env(Path.home() / ".env")
    load_env(Path.home() / ".hermes" / ".env")
    load_env(ROOT / ".env")
    if not REMOTE_DIRS:
        raise SystemExit("KDECK_FTP_REMOTE_DIR is required")
    ftp = connect()
    try:
        ensure_cwd(ftp, REMOTE_DIRS)
        for local, remote in UPLOADS:
            if local.is_file():
                upload_file(ftp, local, remote)
        upload_config(ftp)
    finally:
        ftp.quit()


if __name__ == "__main__":
    main()
